import { EngridLogger } from "./logger";
// a11y means accessibility
// This Component is supposed to be used as a helper for Aria Attributes & Other Accessibility Features

export class A11y {
  private logger: EngridLogger = new EngridLogger(
    "A11y",
    "#FFFFFF",
    "#811212",
    "👁️‍🗨️"
  );

  private observer: MutationObserver | null = null;

  constructor() {
    this.addErrorAlertArea();
    this.addRequired();
    this.addLabel();
    this.addGroupRole();
    this.updateFrequencyLabel();
    const ecardImages: NodeListOf<HTMLImageElement> = document.querySelectorAll('.en__ecarditems__list img');
    this.setAutoGeneratedAltTags(ecardImages);
    this.manageErrorListAlertRole();
    this.observeErrorMessages();
  }

  private addErrorAlertArea() {
    const fieldElements = document.querySelectorAll('.en__field .en__field__element')
    fieldElements.forEach((fieldElement) => {
      if (fieldElement.nextElementSibling?.classList.contains('en__field__error__alert')) return;
      const errorAlert = document.createElement('div');
      errorAlert.setAttribute('aria-live', 'polite');
      errorAlert.setAttribute('aria-atomic', 'true');
      errorAlert.classList.add('en__field__error__alert');
      errorAlert.id = `en__field__error__alert--${Math.random().toString(36).slice(2, 7)}`;
      fieldElement.insertAdjacentElement('afterend', errorAlert);
    })
  }

  private addGroupRole() {
    // Add role="group" to all EN Radio fields
    const radioFields = document.querySelectorAll(".en__field--radio");
    radioFields.forEach((field) => {
      field.setAttribute("role", "group");
      // Add random ID to the label
      const label = field.querySelector("label") as HTMLLabelElement;
      if (label) {
        label.setAttribute(
          "id",
          `en__field__label--${Math.random().toString(36).slice(2, 7)}`
        );
        field.setAttribute("aria-labelledby", label.id);
      }
    });
  }

  private addRequired() {
    const mandatoryFields = document.querySelectorAll(
      ".en__mandatory .en__field__input"
    );
    mandatoryFields.forEach((field) => {
      field.setAttribute("aria-required", "true");
    });
  }

  private addLabel() {
    const otherAmount = document.querySelector(
      ".en__field__input--otheramount"
    ) as HTMLInputElement;
    if (otherAmount) {
      otherAmount.setAttribute(
        "aria-label",
        "Enter your custom donation amount"
      );
    }
    // Split selects usually don't have a label, so let's make the first option the label
    const splitSelects = document.querySelectorAll(
      ".en__field__input--splitselect"
    );
    splitSelects.forEach((select) => {
      const firstOption = select.querySelector("option") as HTMLOptionElement;
      if (
        firstOption &&
        firstOption.value === "" &&
        !firstOption.textContent?.toLowerCase()?.includes("select") &&
        !firstOption.textContent?.toLowerCase()?.includes("choose")
      ) {
        select.setAttribute("aria-label", firstOption.textContent || "");
      }
    });
  }

  // Update the label for the frequency field based on the selected radio button
  private updateFrequencyLabel() {
    const frequencyLabels = document.querySelectorAll('div.en__field__item input[id^="en__field_transaction_recurrfreq"]')
    const frequencyMainLabel = document.querySelector('label[for="en__field_transaction_recurrfreq"]');

    frequencyLabels.forEach((item) => {
      if (item) {

        // Set the label for the checked item on load
        if ((item as HTMLInputElement).checked) {
          frequencyMainLabel?.setAttribute('for', item.id);
        }

        // Then, detect if it changes with the click event
        item.addEventListener('click', () => {
          let frequencyId = item.id;
          frequencyMainLabel?.setAttribute('for', frequencyId);
        });
      }
    })
  }

  private setAutoGeneratedAltTags(images: NodeListOf<HTMLImageElement>): void {
    images.forEach((img: HTMLImageElement) => {
      // Skip if the alt tag is already set
      if (img.alt) return;

      try {
        // Extract the filename from the `src` attribute
        const src: string | null = img.src;
        if (!src) throw new Error("Image src is null or undefined");

        const url = new URL(src);
        const fileNameWithExtension: string | undefined = url.pathname.split('/').pop();
        if (!fileNameWithExtension) throw new Error("No filename found in src");

        // Remove the file extension and replace `-` and `_` with spaces
        let altText: string = fileNameWithExtension.split('.').shift()?.replace(/[-_]/g, ' ') || '';

        // Remove dimensions (#x#) and anything that follows
        altText = altText.replace(/\d+x\d+.*$/, '').trim();

        // Wrap in the disclaimer
        altText = `This is an auto-generated alt tag from the filename: ${altText}`;

        // Set the generated alt text on the image
        img.alt = altText;
      } catch (error) {
        this.logger.danger(`Error processing image: ${img.src}`, error);
      }
    });
  }

  /**
   * Observe #engrid for .en__field__error additions and removals, mirroring
   * text into the per-field .en__field__error__alert live region and toggling
   * aria-invalid / aria-describedby on the corresponding input. Runs for the
   * lifetime of the page so async validators (NeverBounce, VGS, server
   * re-renders) are caught without timing assumptions.
   */
  private observeErrorMessages(): void {
    const root = document.getElementById('engrid') ?? document.body;

    this.observer = new MutationObserver(records => {
      for (const record of records) {
        if (record.type !== 'childList') continue;

        record.addedNodes.forEach(node => {
          if (node instanceof HTMLElement && node.classList.contains('en__field__error')) {
            this.moveErrorMessage(node);
          }
        });

        record.removedNodes.forEach(node => {
          if (!(node instanceof HTMLElement)) return;
          if (!node.classList.contains('en__field__error')) return;
          // node.parentElement is null after removal; record.target is the
          // former parent. Walk up to the enclosing .en__field to be defensive
          // against deeper nesting.
          const fieldWrapper = (record.target as HTMLElement).closest?.('.en__field');
          const alert = fieldWrapper?.querySelector<HTMLElement>('.en__field__error__alert');
          if (alert) this.clearErrorMessage(alert);
        });
      }
    });

    this.observer.observe(root, { childList: true, subtree: true });

    // Initial sweep for errors rendered server-side or by scripts that ran
    // before this observer was attached.
    document.querySelectorAll<HTMLElement>('.en__field').forEach(field => {
      const error = field.querySelector<HTMLElement>('.en__field__error');
      const alert = field.querySelector<HTMLElement>('.en__field__error__alert');
      if (error) this.moveErrorMessage(error);
      else if (alert) this.clearErrorMessage(alert);
    });
  }

  private moveErrorMessage(field: HTMLElement): void {
    if (field.closest('.en__field__error__alert')) return;
    const fieldWrapper = field.closest('.en__field');
    if (!fieldWrapper) return;

    const alertContainer = fieldWrapper.querySelector<HTMLElement>('.en__field__error__alert');
    if (!alertContainer) return;

    alertContainer.textContent = field.textContent;
    field.classList.add('en__field__error--hidden-by-a11y');

    const inputElement = fieldWrapper.querySelector<HTMLElement>(
      '.en__field__element input, .en__field__element select, .en__field__element textarea'
    );
    if (!inputElement) return;

    inputElement.setAttribute('aria-invalid', 'true');
    const describedBy = (inputElement.getAttribute('aria-describedby') ?? '')
      .split(/\s+/)
      .filter(Boolean);
    if (describedBy.indexOf(alertContainer.id) === -1) {
      describedBy.push(alertContainer.id);
    }
    inputElement.setAttribute('aria-describedby', describedBy.join(' '));
  }

  private clearErrorMessage(alert: HTMLElement): void {
    alert.textContent = '';

    const fieldWrapper = alert.closest('.en__field');
    if (!fieldWrapper) return;

    const inputElement = fieldWrapper.querySelector<HTMLElement>(
      '.en__field__element input, .en__field__element select, .en__field__element textarea'
    );
    if (!inputElement) return;

    inputElement.removeAttribute('aria-invalid');
    const remaining = (inputElement.getAttribute('aria-describedby') ?? '')
      .split(/\s+/)
      .filter(id => id && id !== alert.id);
    if (remaining.length) {
      inputElement.setAttribute('aria-describedby', remaining.join(' '));
    } else {
      inputElement.removeAttribute('aria-describedby');
    }
  }

  private manageErrorListAlertRole(): void {
    const errorList = document.querySelector<HTMLUListElement>('ul.en__errorList');
    if (!errorList) return;

    const hasErrorItems = (): boolean => Boolean(errorList.querySelector('li'));

    const enableAlert = (): void => {
      if (!errorList.hasAttribute('role')) {
        errorList.setAttribute('role', 'alert');
      }
    };

    const disableAlert = (): void => {
      if (errorList.hasAttribute('role')) {
        errorList.removeAttribute('role');
      }
    };

    hasErrorItems() ? enableAlert() : disableAlert();

    new MutationObserver(records => {
      for (const record of records) {
        if (record.type === 'childList') {
          hasErrorItems() ? enableAlert() : disableAlert();
          break;
        }
      }
    }).observe(errorList, { childList: true });
  }
}
