// This class is used to expand content when a user clicks on a div with the class "click-to-expand".
// The content is shortened by default and will expand when clicked.

import { ENGrid } from ".";

// Works when the user has adds ".click-to-expand" as a class to any field
export class ClickToExpand {
  clickToExpandWrapper = document.querySelectorAll(
    "div.click-to-expand"
  ) as NodeListOf<HTMLElement>;

  constructor() {
    if (this.clickToExpandWrapper.length) {
      this.clickToExpandWrapper.forEach((element: HTMLElement, index: number) => {
        const textWrapperId = `click-to-expand-text-${index}`;
        const ctaId = `click-to-expand-cta-${index}`;

        // Extract screen reader tip from the live DOM
        const screenReaderTip = element.querySelector(
          ".click-to-expand-screenreader-tip"
        );
        let ariaLabel = "Show more";
        if (screenReaderTip) {
          const tipText = screenReaderTip.textContent?.trim();
          if (tipText) {
            ariaLabel = `Show more: ${tipText}`;
          }
          screenReaderTip.remove();
        }

        // Capture all original child nodes before restructuring
        const originalChildren = Array.from(element.childNodes);

        element.innerHTML = "";

        // Create the text wrapper
        const textWrapper = document.createElement("div");
        textWrapper.className = "click-to-expand-text-wrapper";
        textWrapper.id = textWrapperId;
        textWrapper.setAttribute("aria-hidden", "true");
        textWrapper.setAttribute("aria-label", "Expanded content" + (ariaLabel ? `${ariaLabel.replace('Show more', '')}` : ""));
        textWrapper.setAttribute("tabindex", "-1");

        originalChildren.forEach((child) => {
          textWrapper.appendChild(child);
        });

        const cta = document.createElement("div");
        cta.className = "click-to-expand-cta";
        cta.id = ctaId;
        cta.setAttribute("role", "button");
        cta.setAttribute("tabindex", "0");
        cta.setAttribute("aria-expanded", "false");
        cta.setAttribute("aria-controls", textWrapperId);
        cta.setAttribute("aria-label", ariaLabel);

        element.appendChild(textWrapper);
        element.appendChild(cta);

        const expand = () => {
          if (ENGrid.debug) {
            console.log("A click-to-expand div was expanded");
          }
          element.classList.add("expanded");
          cta.setAttribute("aria-expanded", "true");
          cta.setAttribute("aria-hidden", "true");
          textWrapper.setAttribute("aria-hidden", "false");
          textWrapper.focus(); // Move focus to revealed content for screen reader announcement
        };

        element.addEventListener("click", expand);
        element.addEventListener("keydown", (event) => {
          if ((event as KeyboardEvent).key === "Enter") {
            expand();
          } else if ((event as KeyboardEvent).key === " ") {
            expand();
            event.preventDefault(); // Prevents the page from scrolling
            event.stopPropagation(); // Prevent a console error generated by LastPass https://github.com/KillerCodeMonkey/ngx-quill/issues/351#issuecomment-476017960
          }
        });
      });
    }
  }
}
